# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://takotab.github.io/nbdev_vscode/"

git_url = "https://github.com/takotab/nbdev_vscode/tree/master/"

def custom_doc_links(name): return None
